name: multiconteneur

services:
    mysql:
        image: mysql:8.3.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: springboot
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            -   ./infra/mysql/dump:/docker-entrypoint-initdb.d
    appapi:
        build:
            context: ./apiSpringboot
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        volumes:
            -   ./apiSpringboot:/app
    appweb:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            -   ./AppWeb-0.0.1-SNAPSHOT.jar:/app