name: multiconteneur

services:
    jenkins:
        image: 'yacinerafes/webspringboot2025:latest'
        container_name: "webspringboot2025"
        labels:
            kompose.service.type: nodeport
        ports:
            - '3306:3306'
            - '9000:9000'
            - '8080:8080'
        volumes:
            - /infra/mysql/dump:/springboot.sql
            - /infra/jenkins:/var/jenkins_config
volumes:
    jenkins_data:
        driver: local