name: multiconteneur

services:
    jenkins:
        image: 'yacinerafes/webspringboot2025:latest'
        container_name: "webspringboot2025"
        labels:
            kompose.service.type: nodeport
        ports:
            - '9595:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - /infra/mysql/dump:/springboot.sql
            - /infra/jenkins:/var/jenkins_config
volumes:
    jenkins_data:
        driver: local