name: multiconteneur

services:
    mysql:
        image: mysql:8.0.19
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: springboot
            MYSQL_USER: springboot_user
            MYSQL_PASSWORD: springboot_password
        ports:
            - "3306:3306"
        volumes:
            -   ./infra/mysql/dump:/docker-entrypoint-initdb.d
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        environment:
#            PMA_HOST: mysql
#            PMA_PORT: 3306
#        ports:
#            - "8082:80"
    appapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            -   ./apiSpringboot-0.0.1-SNAPSHOT.jar:/app.jar
    appweb:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9090:9090"
        volumes:
            -   ./AppWeb-0.0.1-SNAPSHOT.jar:/app.jar