name: multiconteneur

services:
    mysql:
        image: mysql:8.0.36
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: springboot
            MYSQL_USER: springboot_user
            MYSQL_PASSWORD: springboot_password
        ports:
            - "3307:3306"
        volumes:
            -   C:/Users/USER-10/IdeaProjects/springbootAPIWEB/apiSpringboot/infra/mysql/dump/springboot.sql:/docker-entrypoint-initdb.d/springboot.sql
    api:
        depends_on:
            -   mysql
        image: yacinerafes/apispringboot:latest
        ports:
            - "9000:80"
    web:
        depends_on:
            -   api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9090:80"
        volumes:
            -   ./AppWeb-0.0.1-SNAPSHOT.jar:/app.jar