name: multiconteneur

services:
    jenkins:
        image: 'jenkins'
        container_name: "jenkins"
        labels:
            kompose.service.type: nodeport
        ports:
            - '9595:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - /infra/jenkins_data:/jenkins_home
            - /infra/jenkins:/var/jenkins_config
volumes:
    jenkins_data:
        driver: local